### ISSUE TITLE
Congratulations and question about ozzo and i18n

### ISSUE THREAD

**Issue by frederikhors** [erdaltsksn/gonca#13]
Congratulations for this project! Great ideas well assembled.

I found out here: https://github.com/go-ozzo/ozzo-validation/issues/102#issuecomment-618754791.

Can I ask you about i18n and ozzo validation?

**Comment by erdaltsksn** [comment]
Of course.

NOTE: I modularize the i18n system. you can check out the following repository for the library.

[https://github.com/erdaltsksn/t](https://github.com/erdaltsksn/t)

If you have any other questions, you're welcome.
